### ISSUE TITLE
User can search entry/entries

### ISSUE THREAD

**Issue by Kenneth-Y-Wang** [Kenneth-Y-Wang/code-journal#9]
## 💰 Motivation

If a user want to search the saved entries, they will be able to target any entry with keywords. 

## 📐 Plan

Allow users to type in key words to search entries and display the result entries in entries screen.

## ✅ Task List

- [x] Add search bar in the header section that allows user to type in keywords
- [x] Add a search button that will allow take the key words next to the search bar
- [x] when the search button is clicked, the screen will automatically show the entries page 
- [x] Any entry’s title or notes has key word included, will show on the page. If not, will hide.
- [x] Add one more ‘show all’ button on the entries page, once it’s clicked, all entries will show. 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
